{% extends '_base.html' %}
{% block content %}
  <div class="main-body">
    <div class="container">
      <div class="col-12 py-md-5 bd-content">
	<h3 class="mb-4">AuthProxy Error Page</h3>
	<div class="card-wrapper card-space">
	  <div class="card card-bg no-after">
	    <div class="card-body">
	      <div class="row">
		<div class="col-sm">
		  <ul class="list-group list-group-flush" style="padding-left: 0;">
		    <li class="mt-2 list-group-item">
		      <p></p>
		      <p>Dear User,</p>
		      <p>There has been an exception in managing your Authentication flow.
			This cannot depend on your credentials, otherwise it would have been the
			page where you entered these to provide you with a Failed
			Authentication notice.
		      </p>
		      <p>The problem you have encountered has been communicated in real time
			to the platform administrators, in the event that it was a temporary
			problem we ask you to:
		      </p>
		      <p>- Try to authenticate again, starting from the page of the service provider website;<br>
			- If the problem occurs again, wait a few minutes and try again;<br>
			- If the problem persists for more than 1 hour, we ask you to open a support ticket at https://ticket.example.org
		      </p>
		      <p>In most cases, it is a temporary problem that arose following an
			update of the platforms in progress, an advancement of the software
			version or a server migration.
		      </p>
		      <p></p>
		    </li>
		  </ul>
		</div>
	      </div>
	    </div>
	  </div>
	</div>
      </div>
    </div>
  </div>
  </div>
{% endblock %}
